name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # Step 2: Set up JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Step 3: Build with Maven
      - name: Build with Maven
        run: mvn clean install

      # Step 4: Generate Javadoc
      - name: Generate Javadoc
        run: mvn javadoc:javadoc

      # Step 5: Publish Javadoc to GitHub Pages
      - name: Publish Javadoc
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages        # The branch where GitHub Pages is served from
          folder: target/site/apidocs  # The folder containing the generated Javadoc
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
